#!/bin/bash
#Network-in!
#Demarrage de l'interface graphique d'un routeur
#V. Verdon
#Version 20250610
###################
REP_NETW=$(dirname $0)
PID_INTERFACE=/var/run/nid_interface

wish $REP_NETW/interface/init.tcl &
echo $(jobs -p %%) > $PID_INTERFACE

#Retablissement des routes statiques du routeur
sysctl -w net.ipv4.ip_forward=1
if [ -e $REP_NETW/routage/routage_on.sh ]
then
	while ! systemctl is-active networking.service
	do
	sleep 1
		$REP_NETW/routage/routage_on.sh
	done
fi
