#!/bin/bash
#Network-in!
#Demarrage de l'interface graphique d'un routeur
#V. Verdon
#Version 20231227
###################
REP_NETW=$(dirname $0)
PID_INTERFACE=/var/run/nid_interface

wish $REP_NETW/interface/init.tcl &
echo $(jobs -p %%) > $PID_INTERFACE

#Retablissement des routes statiques du routeur
echo 1 > /proc/sys/net/ipv4/ip_forward
if [ -e $REP_NETW/routage/routage_on.sh ]
then
	while ! systemctl is-active networking.service
	do
	sleep 1
		$REP_NETW/routage/routage_on.sh
	done
fi
