::ttk::fsdialog::mcflmset {
    Accessed				{Letzter Zugriff}
    Apply				Übernehmen
    Cancel				Abbrechen
    {Cannot change to the directory "%s"} \
      {Kann nicht in das Verzeichnis "%s" wechseln}
    {Cannot create directory "%s"} \
      {Das Verzeichnis "%s" kann nicht angelegt werden}
    Changed				Angepasst
    {Choose Directory}			{Ordner auswählen}
    {Create new folder}			{Neuen Ordner erstellen}
    {Create new folder in}		{Neuer Ordner erstellen in}
    {Display options}			Anzeigeoptionen
    Filter				Dateityp
    Folder				Ordner
    {Go back}				Zurück
    {Go forward}			Vorwärts
    {Go to home directory}		{Gehe zum Benutzerverzeichnis}
    {Go up}				{Nach oben}
    Group				Gruppe
    Inode				Inode
    Location				Ort
    Modified				Geändert
    Name				Name
    {New Folder}			{Neuer Ordner}
    OK					OK
    Open				Öffnen
    Owner				Besitzer
    Permissions				Berechtigungen
    Refresh				{Neu laden}
    Save				Speichern
    {Save As}				{Speichern unter}
    Size				Größe
    {View Display Style}		Anzeigestil
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Kompakt
    {Detailed information to show}	{&Wählen Sie die anzuzeigenden Felder}
    Details				&Details
    {Folders First}			{&Ordner zuerst}
    Reverse				&Umgekehrt
    {Separate Folders}			S&eitenleiste
    {Show Hidden Files}			{&Verborgene Dateien anzeigen}
    Sorting				&Sortierung
    {View mode}				&Ansichtsmodus
    {View options}			A&nsichtseinstellungen
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Keine Berechtigung}
    {No such file or directory}		{Datei oder Verzeichnis nicht gefunden}
    {Not a directory}			{Ist kein Verzeichnis}
    {File exists}			{Die Datei existiert bereits}
    {Input/output error}		Eingabe-/Ausgabefehler
    {Too many levels of symbolic links}	{Zu viele Ebenen aus symbolischen Links}
    {File name too long}		{Der Dateiname ist zu lang}
    {Cannot allocate memory}		{Nicht genügend Hauptspeicher verfügbar}
    {No space left on device} \
      {Auf dem Gerät ist kein Speicherplatz mehr verfügbar}
    {Operation not permitted}		{Die Operation ist nicht erlaubt}
    {Read-only file system}		{Das Dateisystem ist nur lesbar}
}
