::ttk::fsdialog::mcflmset {
    Accessed				Accessed
    Apply				Apply
    Cancel				Cancel
    {Cannot change to the directory "%s"} \
      {Cannot change to the directory "%s"}
    {Cannot create directory "%s"}	{Cannot create directory "%s"}
    Changed				Changed
    {Choose Directory}			{Choose Directory}
    {Create new folder}			{Create new folder}
    {Create new folder in}		{Create new folder in}
    {Display options}			{Display options}
    Filter				Filter
    Folder				Folder
    {Go back}				{Go back}
    {Go forward}			{Go forward}
    {Go to home directory}		{Go to home directory}
    {Go up}				{Go up}
    Group				Group
    Inode				Inode
    Location				Location
    Modified				Modified
    Name				Name
    {New Folder}			{New Folder}
    OK					OK
    Open				Open
    Owner				Owner
    Permissions				Permissions
    Refresh				Refresh
    Save				Save
    {Save As}				{Save As}
    Size				Size
    {View Display Style}		{View Display Style}
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Compact
    {Detailed information to show}	{Detailed &information to show}
    Details				&Details
    {Folders First}			{&Folders First}
    Reverse				&Reverse
    {Separate Folders}			{S&eparate Folders}
    {Show Hidden Files}			{Show &Hidden Files}
    Sorting				&Sorting
    {View mode}				{View &mode}
    {View options}			{View &options}
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Permission denied}
    {No such file or directory}		{No such file or directory}
    {Not a directory}			{Not a directory}
    {File exists}			{File exists}
    {Input/output error}		{Input/output error}
    {Too many levels of symbolic links}	{Too many levels of symbolic links}
    {File name too long}		{File name too long}
    {Cannot allocate memory}		{Cannot allocate memory}
    {No space left on device}		{No space left on device}
    {Operation not permitted}		{Operation not permitted}
    {Read-only file system}		{Read-only file system}
}
