::ttk::fsdialog::mcflmset {
    Accessed				Accédé
    Apply				Appliquer
    Cancel				Annuler
    {Cannot change to the directory "%s"} {Impossible de se déplacer dans le dossier "%s"}
    {Cannot create directory "%s"}	{Impossible de créer le dossier %s}
    Changed				Changé
    {Choose Directory}			{Choisir le dossier}
    {Create new folder}			{Créer un nouveau dossier}
    {Create new folder in}		{Créer un nouveau dossier dans}
    {Display options}			{Options d'affichage}
    Filter				Filtre
    Folder				Dossier
    {Go back}				{Retour arrière}
    {Go forward}			{Aller en avant}
    {Go to home directory}		{Aller au dossier personnel}
    {Go up}				{Aller au dossier parent}
    Group				Groupe
    Inode				Inode
    Location				Localisation
    Modified				Modifié
    Name				Nom
    {New Folder}			{Nouveau dossier}
    OK					OK
    Open				Ouvrir
    Owner				Propriétaire
    Permissions				Permissions
    Refresh				Rafraichir
    Save				Enregistrer
    {Save As}				{Enregistrer sous}
    Size				Taille
    {View Display Style}		{Style d'affichage}
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Compact
    {Detailed information to show}	{&Informations détaillées à montrer}
    Details				&Details
    {Folders First}			{Dossie&rs en premier}
    Reverse				I&nverser
    {Separate Folders}			{Dossiers sé&parés}
    {Show Hidden Files}			{Montrer les fic&hiers cachés}
    Sorting				&Tri
    {View mode}				{&Mode d'affichage}
    {View options}			{&Options d'affichage}
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Pas les permissions nécessaires}
    {No such file or directory}		{Fichier ou dossier inexistant}
    {Not a directory}			{Pas un dossier}
    {File exists}			{Le fichier existe}
    {Input/output error}		{Erreur d'entrée/sortie}
    {Too many levels of symbolic links} {Trop de niveaux de liens symboliques}
    {File name too long}		{Nom de fichier trop long}
    {Cannot allocate memory}		{Allocation mémoire impossible}
    {No space left on device}		{Plus d'espace disponible sur le disque}
    {Operation not permitted}		{Opération non permise}
    {Read-only file system}		{Système de fichiers en lecture seule}
}
