::ttk::fsdialog::mcflmset {
    Accessed				Geopend
    Apply				Toepassen
    Cancel				Annuleren
    {Cannot change to the directory "%s"} \
      {Map "%s" kan niet worden geopend}
    {Cannot create directory "%s"}	{Kan map %s niet aanmaken}
    Changed				Aangepast
    {Choose Directory}			{Map kiezen}
    {Create new folder}			{Nieuwe map aanmaken}
    {Create new folder in}		{Nieuwe map aanmaken in}
    {Display options}			{Weergavestijl aanpassen}
    Filter				Filter
    Folder				Map
    {Go back}				Terug
    {Go forward}			Vooruit
    {Go to home directory}		{Naar persoonlijke map}
    {Go up}				Omhoog
    Group				Groep
    Inode				Inode
    Location				Locatie
    Modified				Gewijzigd
    Name				Naam
    {New Folder}			{Nieuwe map}
    OK					OK
    Open				Openen
    Owner				Eigenaar
    Permissions				Rechten
    Refresh				Vernieuwen
    Save				Opslaan
    {Save As}				{Opslaan als}
    Size				Grootte
    {View Display Style}		Weergavestijl
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Compact
    {Detailed information to show}	{Wee&r te geven details}
    Details				&Details
    {Folders First}			{&Mappen eerst}
    Reverse				&Aflopend
    {Separate Folders}			{Ma&ppen apart weergeven}
    {Show Hidden Files}			{&Verborgen bestanden tonen}
    Sorting				&Sorteren
    {View mode}				&Weergavemodus
    {View options}			W&eergave-opties
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Toegang geweigerd}
    {No such file or directory}		{Bestand of map bestaat niet}
    {Not a directory}			{Is geen map}
    {File exists}			{Bestand bestaat al}
    {Input/output error}		Invoer-/uitvoerfout
    {Too many levels of symbolic links} \
      {Te veel niveaus van symbolische koppelingen -- vermoedelijk een lus}
    {File name too long}		{Bestandsnaam is te lang}
    {Cannot allocate memory}		{Onvoldoende geheugen beschikbaar}
    {No space left on device}		{Geen ruimte meer over op apparaat}
    {Operation not permitted}		{Actie is niet toegestaan}
    {Read-only file system}		{Bestandssysteem is alleen-lezen}
}
