::ttk::fsdialog::mcflmset {
    Accessed				{Czas dostępu}
    Apply				Zastosuj
    Cancel				Zaniechaj
    {Cannot change to the directory "%s"} \
      {Nie udało się przejść do katalogu
"%s"}
    {Cannot create directory "%s"}	{Nie można utworzyć katalogu "%s"}
    Changed				Zmiana
    {Choose Directory}			{Wybierz katalog}
    {Create new folder}			{Utwórz nowy folder}
    {Create new folder in}		{Utwórz nowy katalog w}
    {Display options}			{Ustawienia widoku}
    Filter				{Rodzaj pliku}
    Folder				Katalog
    {Go back}				{Idź wstecz}
    {Go forward}			Naprzód
    {Go to home directory}		{Idź do katalogu domowego}
    {Go up}				{Idź do góry}
    Group				Grupa
    Inode				Inode
    Location				Lokalizacja
    Modified				Zmieniony
    Name				Nazwa
    {New Folder}			{Nowy katalog}
    OK					OK
    Open				Otwórz
    Owner				Właściciel
    Permissions				{Prawa dostępu}
    Refresh				Odśwież
    Save				Zapisz
    {Save As}				{Zapisz pod nazwą}
    Size				Rozmiar
    {View Display Style}		{Wygląd widoku}
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Zwarty
    {Detailed information to show}	{&Wybierz pokazywane pola}
    Details				&Szczegóły
    {Folders First}			{&Najpierw katalogi}
    Reverse				&Odwrotnie
    {Separate Folders}			{&Katalogi osobno}
    {Show Hidden Files}			{&Pokaż ukryte pliki}
    Sorting				So&rtowanie
    {View mode}				{&Tryb widoku}
    {View options}			{&Ustawienia widoku}
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Brak dostępu}
    {No such file or directory}		{Nie ma takiego pliku ani katalogu}
    {Not a directory}			{Nie jest katalogiem}
    {File exists}			{Plik istnieje}
    {Input/output error}		{Błąd wejścia/wyjścia}
    {Too many levels of symbolic links} \
      {Za duże zagnieżdżenie dowiązań symbolicznych}
    {File name too long}		{Za długa nazwa pliku}
    {Cannot allocate memory}		{Nie można przydzielić pamięci}
    {No space left on device}		{Brak miejsca na urządzeniu}
    {Operation not permitted}		{Operacja niedozwolona}
    {Read-only file system}		{System plików wyłącznie do odczytu}
}
