::ttk::fsdialog::mcflmset {
    Accessed				Acessado
    Apply				Aplicar
    Cancel				Cancelar
    {Cannot change to the directory "%s"} \
      {Não é possível visualizar a pasta "%s"}
    {Cannot create directory "%s"} \
      {Não foi possível criar o diretório "%s"}
    Changed				Alterado
    {Choose Directory}			{Escolher a pasta}
    {Create new folder}			{Criar nova pasta}
    {Create new folder in}		{Criar nova pasta em}
    {Display options}			{Opções de exibição}
    Filter				Filtro
    Folder				Pasta
    {Go back}				Voltar
    {Go forward}			Avançar
    {Go to home directory}		{Ir para o diretório home}
    {Go up}				{Ir pra cima}
    Group				Grupo
    Inode				Inode
    Location				Localização
    Modified				Modificado
    Name				Nome
    {New Folder}			{Nova pasta}
    OK					Ok
    Open				Abrir
    Owner				Dono
    Permissions				Permissões
    Refresh				Atualizar
    Save				Salvar
    {Save As}				{Salvar como}
    Size				Tamanho
    {View Display Style}		{Estilo de exibição}
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Compacto
    {Detailed information to show}	{&Escolha os campos a serem mostrados}
    Details				&Detalhes
    {Folders First}			{&Pastas primeiro}
    Reverse				{&Ao contrário}
    {Separate Folders}			{&Separar pastas}
    {Show Hidden Files}			{Mos&trar arquivos ocultos}
    Sorting				&Filtragem
    {View mode}				{&Modo de exibição}
    {View options}			{&Opções de visualização}
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Permissão negada}
    {No such file or directory}		{Arquivo ou diretório inexistente}
    {Not a directory}			{Não é um diretório}
    {File exists}			{Arquivo existe}
    {Input/output error}		{Erro de entrada/saída}
    {Too many levels of symbolic links}	{Muitos níveis de links simbólicos}
    {File name too long}		{Nome de arquivo muito longo}
    {Cannot allocate memory}		{Não foi possível alocar memória}
    {No space left on device} \
      {Não há espaço disponível no dispositivo}
    {Operation not permitted}		{Operação não permitida}
    {Read-only file system} \
      {Sistema de arquivos somente para leitura}
}
