::ttk::fsdialog::mcflmset {
    Accessed				Доступ
    Apply				Apply
    Cancel				Отмена
    {Cannot change to the directory "%s"} \
      {Ошибка при переходе в каталог "%s"}
    {Cannot create directory "%s"}	{Невозможно создать каталог "%s"}
    Changed				Изменено
    {Choose Directory}			{Выбор каталога}
    {Create new folder}			{Создать новую папку}
    {Create new folder in}		{Создать каталог в}
    {Display options}			{Параметры просмотра}
    Filter				Фильтр
    Folder				Каталог
    {Go back}				Назад
    {Go forward}			Вперёд
    {Go to home directory}		{В начальный каталог}
    {Go up}				{Перейти вверх}
    Group				Группа
    Inode				Inode
    Location				Расположение
    Modified				Изменён
    Name				Имя
    {New Folder}			{Создать каталог}
    OK					OK
    Open				Открыть
    Owner				Владелец
    Permissions				{Права доступа}
    Refresh				Обновить
    Save				Сохранить
    {Save As}				{Сохранить как}
    Size				Размер
    {View Display Style}		{Режим просмотра}
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Столбцы
    {Detailed information to show}	{&Выберите показываемые поля}
    Details				&Таблица
    {Folders First}			{&Каталоги сначала}
    Reverse				&Обратная
    {Separate Folders}			{С&писок каталогов}
    {Show Hidden Files}			{Пок&азать скрытые файлы}
    Sorting				Сорт&ировка
    {View mode}				{&Режим просмотра}
    {View options}			{&Параметры просмотра}
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Отказано в доступе}
    {No such file or directory}		{Нет такого файла или каталога}
    {Not a directory}			{Это не каталог}
    {File exists}			{Файл существует}
    {Input/output error}		{Ошибка ввода/вывода}
    {Too many levels of symbolic links} \
      {Слишком много уровней символьных ссылок}
    {File name too long}		{Слишком длинное имя файла}
    {Cannot allocate memory}		{Невозможно выделить память}
    {No space left on device} \
      {На устройстве не осталось свободного места}
    {Operation not permitted}		{Операция не позволена}
    {Read-only file system} \
      {Файловая система доступна только для чтения}
}
