::ttk::fsdialog::mcflmset {
    Accessed				Använd
    Apply				Verkställ
    Cancel				Avbryt
    {Cannot change to the directory "%s"} \
      {Kan ej skifta till mappen "%s"}
    {Cannot create directory "%s"}	{Kan inte skapa katalog "%s"}
    Changed				Skapad
    {Choose Directory}			{Välj katalog}
    {Create new folder}			{Skapa ny mapp}
    {Create new folder in}		{Skapa ny mapp i}
    {Display options}			Visningsalternativ
    Filter				Filter
    Folder				Mapp
    {Go back}				{Gå tillbaka}
    {Go forward}			{Gå framåt}
    {Go to home directory}		{Gå till hemkatalog}
    {Go up}				{Gå uppåt}
    Group				Grupp
    Inode				Inode
    Location				Plats
    Modified				Ändrad
    Name				Namn
    {New Folder}			{Ny mapp}
    OK					OK
    Open				Öppna
    Owner				Ägare
    Permissions				Behörigheter
    Refresh				Uppdatera
    Save				Spara
    {Save As}				{Spara som}
    Size				Storlek
    {View Display Style}		Visningsstil
}

# Make sure these all have a different letter following the &
::ttk::fsdialog::mcflmset {
    Compact				&Kompakt
    {Detailed information to show}	{V&älj vilka fält som ska visas}
    Details				&Detaljer
    {Folders First}			{&Mappar först}
    Reverse				&Omvänd
    {Separate Folders}			{M&appar separat}
    {Show Hidden Files}			{V&isa dolda filer}
    Sorting				&Sortering
    {View mode}				&Visningsläge
    {View options}			Vis&ningsalternativ
}

# Posix error messages
::ttk::fsdialog::mcflmset {
    {Permission denied}			{Åtkomst nekas}
    {No such file or directory}		{Filen eller katalogen finns inte}
    {Not a directory}			{Inte en katalog}
    {File exists}			{Filen existerar}
    {Input/output error}		In/ut-fel
    {Too many levels of symbolic links}	{För många nivåer av symboliska länkar}
    {File name too long}		{För långt filnamn}
    {Cannot allocate memory}		{Kan inte allokera minne}
    {No space left on device}		{Enheten är full}
    {Operation not permitted}		{Operationen inte tillåten}
    {Read-only file system}		{Skrivskyddat filsystem}
}
