#!/bin/bash
#Network-in!
#Demarrage de l'interface graphique d'un PC
#V. Verdon
#Version 20241229
###################
REP_NETW=$(dirname $0)
PID_INTERFACE=/var/run/nid_interface

# Si PC serveur, copie modèle fichier index pour serveur Web
if [ -e $REP_NETW/services/index.html ]
then
    mv $REP_NETW/services/index.html /var/www/html
    ID=$(cat $REP_NETW/com/id)
    sed -i "s/noname/$ID/" /var/www/html/index.html
fi

wish $REP_NETW/interface/init.tcl &
echo $(jobs -p %%) > $PID_INTERFACE
echo $WINDOWID > $REP_NETW/com/window_id
