#!/usr/bin/tclsh
####################################################################
#Programme écrit par V. Verdon
#Network-in est un simulateur de réseau
#placé sous licence GNU GPL (consulter le fichier joint intitulé "licence.txt"
# commande ifconfig modifiée pour cacher eth99
####################################################################
# Version du 17/05/2011

# nom de l'interface à supprimer
set interf_supp eth99

if {$interf_supp ==  [lindex $argv end]} {
  puts "$interf_supp: error fetching interface information: Device not found"
  exit
}

set a [catch {set res [eval exec /sbin/ifconfig $argv]} err]
if {$a == {1}} {
  puts $err
  exit
}
set res [split $res \n]
set long [llength $res]

for {set i 0} {$i < $long} {incr i} {
  set ligne [lindex $res $i]
  if {[string first $interf_supp $ligne] != {-1}} {
    break
  } else  {
    puts $ligne
  }
}
for {set j [expr $i + 1]} {$j < $long} {incr j} {
  set ligne [lindex $res $j]
  if {$ligne == {}} {
    break
  } else  {
    #rien
  }
}
for {set k [expr $j + 1]} {$k < $long} {incr k} {
  set ligne [lindex $res $k]
  puts $ligne
}
 
