#!/bin/bash
####################################################################
#Programme écrit par V. Verdon
#Network-in est un simulateur de réseau
#placé sous licence GNU GPL (consulter le fichier joint intitulé "licence.txt")
#Version 20250426
####################################################################
REP_INS=$(dirname $0)
#Repertoire de l'application
REP=/usr/lib/network-in

# sudo needs hostname resolution
HOSTNAME=$(hostname)
if [ -z "$(grep $HOSTNAME /etc/hosts)" ]
then
  echo "127.0.0.1  $HOSTNAME" >> /etc/hosts
fi

# Add networkin-cap account for captures
useradd -g wireshark -s /bin/bash networkin-cap

# Add lines in sudoers
cat <<EOF>> /etc/sudoers

# Network-In! Simulator sudo auth
ALL  ALL=NOPASSWD:$REP/bin/network-in-start
ALL  ALL=NOPASSWD:$REP/bin/network-in-stop
ALL  ALL=NOPASSWD:$REP/bin/conf_gateway
ALL  ALL=NOPASSWD:$REP/bin/conf_bridge
ALL  ALL=NOPASSWD:/usr/lib/network-in/bin/conf_capture
ALL  ALL=(networkin-cap) NOPASSWD:/usr/bin/wireshark
EOF
chmod 0440 /etc/sudoers
sudo -v

# Symlink libvde creation
#LIBVDE=$(find /usr/lib -name 'libvdeplug.so.*' -type f 2>/dev/null | sort | tail -n 1)
#ln -s $LIBVDE $(dirname $LIBVDE)/libvdeplug.so 2> /dev/null
# Prise en compte des path lib de /etc/ld.so.conf.d/network-in.conf
ldconfig

# Symlink networkin
ln -s /usr/bin/network-in /usr/bin/networkin 2> /dev/null

exit 0
